### ISSUE TITLE
Throwing error when tried toverify 

### ISSUE THREAD

**Issue by fakesmile9704** [sampathgujarathi/Enron#1]
```Ignoring exception in on_application_command_error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
  File "/usr/local/lib/python3.10/dist-packages/discord/commands/core.py", line 974, in _invoke
    await self.callback(ctx, **kwargs)
  File "/root/discordstuff/Enron/main.py", line 57, in setup
    await verify(bot,ctx,verification_channel,role)
  File "/root/discordstuff/Enron/cogs/utility.py", line 319, in verify
    embed.set_thumbnail(url=ctx.guild.icon.url)
AttributeError: 'NoneType' object has no attribute 'url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "/root/discordstuff/Enron/main.py", line 218, in on_application_command_error
    raise error
  File "/usr/local/lib/python3.10/dist-packages/discord/bot.py", line 1088, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/discord/commands/core.py", line 374, in invoke
    await injected(ctx)
  File "/usr/local/lib/python3.10/dist-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'NoneType' object has no attribute 'url'```

**Comment by GSampath1** [comment]
Hello, Sorry for late reply is the error fixed or do u have issue still?
